"""adding a column

Revision ID: 524d25fd4e48
Revises: 
Create Date: 2023-08-05 21:59:17.576702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524d25fd4e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('reporter_email')

    # ### end Alembic commands ###
